### ISSUE TITLE
依然提示输入字符串不是合法 integer

### ISSUE THREAD

**Issue by yoyojacky** [withsalt/BilibiliLiveTools#2]
树莓派环境:
Raspberry Pi 4B 
系统: Raspbian  Linux raspberrypi 4.19.57-v7l+ #1244 SMP Thu Jul 4 18:48:07 BST 2019 armv7l GNU/Linux
版本: No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
# 参考操作连接: quarkbook.com/?p=733
错误消息: 

> Unhandled exception. System.Exception: Convert result model failed. Input string '160.8' is not a valid integer. Path 'data.userCoinIfo.coins', line 1, position 870.
>    at Bilibili.Api.LiveApi.GetRoomInfo(User user) in E:\CSharp\Projects\BilibiliLiveTools\src\Bilibili\Api\LiveApi.cs:line 135
>    at BilibiliLiveTools.Program.Main(String[] args) in E:\CSharp\Projects\BilibiliLiveTools\src\BilibiliLiveTools\Program.cs:line 63
>    at BilibiliLiveTools.Program.<Main>(String[] args)
> Aborted

**Comment by withsalt** [comment]
能不能把获取房间信息API获取的字符串提供一下，我看哈原因呢？

**Comment by yoyojacky** [comment]
pi@raspberrypi:~/BilibiliLiveTools/src/BilibiliLiveTools/Settings $ cat LiveSetting.json
{
  "LiveCategory": "27",
  "LiveRoomName": "树莓派尝试直播推流",
  "VideoSource": "/tmp/rpicam",
  "AudioSource": "http://media.xxoojoke.com/tingyu/therain.m4a",
  "Resolution": "hd720"
}

**Comment by yoyojacky** [comment]
另外一个user.json是我的账号和密码了，我就不贴出来了哦

**Comment by yoyojacky** [comment]
pi@raspberrypi:~/BilibiliLiveTools_ARM32 $ sudo ./BilibiliLiveTools
[3/19/2020 2:55:17 PM] 用户"13951654176"：登录失败
[3/19/2020 2:55:17 PM] 用户"13916554176"：错误信息：{
  "code": -449,
  "message": "服务繁忙, 请稍后再试",
  "ts": 1584600917
}
[3/19/2020 2:55:17 PM] 账号13916554176登录失败！

**Comment by withsalt** [comment]
更新了登录接口，回头我重新发布一个

**Comment by yoyojacky** [comment]
好的，谢谢大佬！
