### ISSUE TITLE
你好，我想用本地视频推流，为啥报错呢，

### ISSUE THREAD

**Issue by geek2024811** [withsalt/BilibiliLiveTools#20]
|推流过程中发生错误，接口请求失败，接口：https://api.live.bilibili.com/room/v1/Room/update，方法：POST，描述：文 案审核中,请稍等.
成功登录了，是不是要有obs，可以给指导一下吗

**Comment by geek2024811** [comment]
real-time buffer [OBS Virtual Camera] [video input] too full or near too full (136% of size: 3041280 [rtbufsize parameter])! frame dropped! b站可以直播本地视频了，用obs 改了摄像头名字可以

**Comment by withsalt** [comment]
第一个是接口风控了，第二是推流命令没对，可以推流本地视频。

**Comment by geek2024811** [comment]
//ffmpeg -re -i C:\Users\LIXUAN\Desktop\光厂_28920934_李白人物介绍AE模版.mp4 -c copy -f flv "rtmp://live-push.bilivideo.com/live-bvc/?streamname=xxx" 我是在配置文件里面加这个 可以不 虽然直接用obs也可以直播但没有免登录，适合24小时直播类型，

**Comment by geek2024811** [comment]
?streamname=xxx 这个怎么自动获得呢

**Comment by withsalt** [comment]
填这个
ffmpeg -re -i C:\Users\LIXUAN\Desktop\光厂_28920934_李白人物介绍AE模版.mp4 -c copy -f flv [[URL]]
