### ISSUE TITLE
求解，一直报错，试过系统安装的ffmpeg和文件自带的ffmpeg都不行，如下

### ISSUE THREAD

**Issue by wqx2000** [withsalt/BilibiliLiveTools#21]
[tcp @ 0x2c29a300] Failed to resolve hostname live-push.bilivideo.com: System error
[rtmp @ 0x2c239ce0] Cannot open connection tcp://live-push.bilivideo.com:1935?tcp_nodelay=0
，说错了，是系统自带的ffmpeg和文件bin里面自带的ffmpeg的命令都可以正常运行，但是浏览器的操作的反而不可以

**Comment by wqx2000** [comment]
ffmpeg -f concat -safe 0 -re -i "/home/orangepi/Videos/mylist.txt" -vcodec copy -acodec copy -f flv -y  {URL} 用的这个命令

**Comment by withsalt** [comment]
这个怎么看起来是解析不了live-push.bilivideo.com这个域名呢

**Comment by wqx2000** [comment]
😂好像是文件自带的ffmpeg不行，我用系统安装的ffmpeg替换了文件的就可以了
