### ISSUE TITLE
【问题】系统排除5000端口导致程序无法正常运行

### ISSUE THREAD

**Issue by UnrealOfficial** [withsalt/BilibiliLiveTools#25]
如图所示，程序即使以管理员身份运行也会因为无法绑定5000端口而崩溃，尝试过删除排除规则，但是被拒绝访问了
![b1b7b1d4b8b5716eb506b74c25edd5b9](https://github.com/user-attachments/assets/fa7957f7-a58a-41ed-917a-b7380616b9e0)
![image](https://github.com/user-attachments/assets/04bf9e50-5d36-48eb-a9a4-fcabb9e748d2)

**Comment by UnrealOfficial** [comment]
如果可以的话，能否增加一个修改绑定端口的选项？

**Comment by withsalt** [comment]
cmd下执行命令：
BilibiliAutoLiver.exe --urls="http://*:18686"  

端口换成你中意的~
