### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by BoKaiSun** [withsalt/BilibiliLiveTools#6]
需要手机或者邮箱的验证码
命令行中给出的登录url，使用浏览器打开后显示需要验证码。不知道这个问题能不能解决

**Comment by withsalt** [comment]
此问题暂时没有办法，你看看先下载个B站app，然后登陆一下，改下密码，再在工具里面登陆。（PS：尽量不要触发验证码）
可能以后有时间了会解决一哈这个问题😂

**Comment by BoKaiSun** [comment]
> 此问题暂时没有办法，你看看先下载个B站app，然后登陆一下，改下密码，再在工具里面登陆。（PS：尽量不要触发验证码）
> 可能以后有时间了会解决一哈这个问题😂

thanks

**Comment by zxwanghongyi** [comment]
我也是 改了密码也不行 之前没问题 从今天开始就这样了

**Comment by withsalt** [comment]
晚上我看看呢

**Comment by withsalt** [comment]
时隔三个月，已修复。

**Comment by zxwanghongyi** [comment]
太感谢了
